# Generated by Django 4.2.16 on 2024-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('russian', '0002_alter_users_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='event',
            field=models.ManyToManyField(to='russian.event'),
        ),
    ]
