# Generated by Django 5.0.7 on 2024-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('russian', '0003_alter_users_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='point_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
